### ISSUE TITLE
No data source available 

### ISSUE THREAD

**Issue by frankhlchi** [Amanda-Zheng/GNNEvaluator#1]
Hi Amanda,

Thank you for your great work. Could you provide the data source for network dataset? I cannot find a good source to download it to ./data.

Thank you,

**Comment by Amanda-Zheng** [comment]
Hi, Frank, here is the data link in google drive, please check: https://drive.google.com/drive/folders/1RqfrAaXdINmklxbByKUoJxWCD1yfs_c_?usp=sharing

**Comment by frankhlchi** [comment]
Thank you!
